map_name: Catalunya
sim_params:
  mu: 1.0489
  C_Sf: 4.718
  C_Sr: 5.4562
  lf: 0.15875
  lr: 0.17145
  h: 0.074
  m: 3.74
  I: 0.04712
  s_min: -0.4189
  s_max: 0.4189
  sv_min: -3.2
  sv_max: 3.2
  v_switch: 7.319
  a_max: 9.51
  v_min: -5.0
  v_max: 20.0
  width: 0.31
  length: 0.58
actions_conf:
  min_steering: -0.4189
  max_steering: 0.4189
  min_speed: 0.5
  max_speed: 3.0
observations_conf:
  max_range: 10.0
  resolution: 0.25
  degree_fov: 270
  frame_skip: 5
termination_conf:
  max_steps: 1500
  max_lap: 1
  on_collision: True
# for task specification
comfortable_speed_min: 1.5  # m/s
comfortable_speed_max: 2.0  # m/s
comfortable_steering: 0.10  # rad
favourite_lane: 0 # 0 is right lane, 1 is left lane
