gamma: 0.98
learning_rate: 0.00073
buffer_size: 100000
learning_starts: 1000
train_freq: 64
batch_size: 256
tau: 0.02
ent_coef: 'auto'
target_update_interval: 1
gradient_steps: 64
target_entropy: 'auto'
action_noise: null
use_sde: True
policy_kwargs:
  log_std_init: -2
  net_arch: [64, 64]