max_steps: 30

REACTION_TIME: 0.1 # s   # TAU # 0.1-0.5 for humans

# LONGITUDINAL QUANTITIES
ACCEL_MAX: 5 # M / S^2
BRAKE_MAX: 5 # M / S^2
BRAKE_MIN: 1 # M / S^2
JERK_MAX: 2 # M/S^3
BRAKE_ABRUPT: -2.5 # M / S^2
LON_DIST_NORMALIZER: 0.06  #org = 0.4

# LATERAL QUANTITIES
LAT_DIST_MARGIN: 1 # M    # mu
LAT_ACCEL_MAX: 3.5 # M/S^2
LAT_MIN_BR: 0.7 # M/S^2
LAT_MAX_JERK: 1.5 # M/S^3
LAT_DIST_NORMALIZER: 0.02

# HIGHWAY
HARD_SPEED_LIMIT: 25  # M/S   # 90kph = 25 m/s
SOFT_SPEED_LIMIT: 23  # M/S   # 90kph = 25 m/s
SPEED_LOWER_BOUND: 20
SPEED_LIMIT_TOL: 2.7 # M/S   # 10 kph = 2.77 m/s
POST_ENCROACHMENT: 1.5 # S
LANE_WIDTH: 3  # M
VEHICLE_WIDTH: 2   # M
VEHICLE_LENGTH: 5  # M
TARGET_DISTANCE: 750
TARGET_DISTANCE_TOL: 20
LANES_COUNT: 3

X_LIMIT: 2000
Y_LIMIT: 50
VX_LIMIT: 40
VY_LIMIT: 40