# HIGHWAY
max_steps: 30

lanes_count: 3
lane_width: 3  # M
vehicle_width: 2   # M
vehicle_length: 5  # M

target_x: 750
target_distance_tol: 20

x_limit: 2000
y_limit: 50
vx_limit: 40
vy_limit: 40

speed_lower_bound: 20
speed_upper_bound: 30
speed_tol: 5

