task: "forward_hardcore"
# episode definition
max_steps: 500
terminate_on_collision: True
hardcore: True
# simulation parameters
dist_hull_limit: 0.225 # empirically chosen, this is the dist to collision estimated as min(lidar) (norm in 0,1)
angle_hull_limit: 0.08726 # ~ 25 degree
speed_y_limit: 0.1  # domain in [0,1], 0.5 choosen arbitrarly
angle_vel_limit: 0.25
speed_x_target: 0.30
