scenario_files:
  - treitlstrasse_multi_agent.yml
order: random
max_steps: 6000             # sim steps, depends on integration step
n_last_actions: 3           # nr last actions to include in the observation
