scenario_files:
  - treitlstrasse_v3.yml
frame_skip: 5
max_steps: 3000
#
l2d_max_range: 20.0
l2d_res: 0.25
max_halflane: 1.5     # max half-width of the track in meters, it is used for clipping the estimated dist_to_wall
#
min_speed: 0.5
max_speed: 3.0
min_steering: -0.4189
max_steering: +0.4189
wheel_base: 0.3205
control_curvature: False
#
norm_speed_limit: 0.34    # speed [0,3] m/s normalized in [-1,+1], then 0.34 approx. 2 m/s
norm_comf_steering: 0.25  # steer [-.42,+.42] rads norm. in [-1, +1], then +-0.25 approx. +-6 deg
comf_dist_to_wall: 0.40   # desired unnormalized dist to right wall (meters)
tolerance_margin: 0.05    # tolerance of error in keeping the target distance to the right wall (meters)