world:
  name: treitlstrasse
agents:
  - id: A
    vehicle:
      name: racecar
      sensors: [ lidar, pose, velocity, acceleration ]
      actuators: [ speed, steering ]
    task:   # not used but required to use default constructor racecar_gym
      task_name: maximize_progress
      params: {laps: 1, time_limit: 120.0, terminate_on_collision: True}