gamma: 0.99
learning_rate: 0.0003
buffer_size: 50000
learning_starts: 100
train_freq: 1
batch_size: 64
tau: 0.005
ent_coef: 'auto'
target_update_interval: 1
gradient_steps: 1
target_entropy: 'auto'
action_noise: null
policy_kwargs: {}