gamma: 0.99
learning_rate: 0.0003
buffer_size: 300000
learning_starts: 10000
train_freq: 64
batch_size: 256
tau: 0.01
ent_coef: 'auto'
target_update_interval: 1
gradient_steps: 64
target_entropy: 'auto'
action_noise: null
use_sde: True
policy_kwargs:
  log_std_init: -3
  net_arch: [400, 300]