gamma: 0.99
learning_rate: 0.00073
buffer_size: 300000
learning_starts: 10000
train_freq: 1
batch_size: 256
tau: 0.01
ent_coef: 'auto'
target_update_interval: 1
gradient_steps: 1
policy_kwargs:
  net_arch: [400, 300]