task: 'land'
# episode def
fuel_usage: 0.005  # Every non-zero action depletes this percentage (values in [0,1])
FPS: 50   # do not change this, it will alter the simulated physics
max_steps: 600
# target
x_target: 0.0  # fixed from environment, helipad is always at (0,0) # Do not change
y_target: 0.0
halfwidth_landing_area: 0.15 # width of the landing area is +- this value
# comfort
angle_limit: 1.0471975511965976 # pi/3
angle_speed_limit: 0.5 # arbitrary
# starting conditions
obstacle_lowleft_x: 9.0  # represents x-coord lower-left corner
obstacle_lowleft_y: 7.0  # represents y-coord lower-left corner
obstacle_width: 2.0
obstacle_height: 0.5
initial_x_offset: 2.0  # sampling craft from x=0.0 +- offset