learning_rate: 0.00003
n_steps: 512
batch_size: 128
n_epochs: 20
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: True
sde_sample_freq: 4
target_kl: null
