gamma: 0.99
learning_rate: 0.0003
buffer_size: 1000000
learning_starts: 100
train_freq: 1
batch_size: 256
tau: 0.005
ent_coef: 'auto'
target_update_interval: 1
gradient_steps: 1
target_entropy: 'auto'
action_noise: null
use_sde: True
policy_kwargs:
  net_arch:
    qf: [256, 256]
    pi: [64, 64]