learning_rate: 0.0001
buffer_size: 100000
learning_starts: 100
batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
optimize_memory_usage: False
ent_coef: 'auto'
target_update_interval: 1
target_entropy: 'auto'
use_sde: True
sde_sample_freq: 4
use_sde_at_warmup: False
